// Context-aware prompt system for Guessing Game and QuickDraw
// - quickdrawConcepts: used by QuickDraw
// - phraseTemplates: templates with typed placeholders like (character), (ridable), (weapon)
// - adjectives: generic adjectives used by (adj)
// - lexicon: word bank with tags to enable contextual filling
const prompts = {
  // Broad, open-ended concept prompts for QuickDraw (encourage scene interpretation)
  quickdrawConcepts: [
    'love','winter','sports','celebration','music','chaos','friendship','future technology',
    'nature','adventure','dreams','festival','storm','silence','growth','time','journey',
    'memory','rebellion','world','desert oasis','haunted house',
    'space colony','ancient ruins','marketplace','island','escape','teamwork',
    'mystery','balance','reflection','flight','ocean','forest spirits',
    'underwater civilization','enchanted forest','city skyline','picnic','bakery','night market',
    'junkyard','time travel','portal','campfire','parade','circus','snow day',
    'beach day','garden','library','arcade', 'pirates','coral reef','volcano eruption','safari',
    'mountain climb','treasure hunt','alien life', 'meteor shower','train station','rooftop',
    'lighthouse','shipwreck','rainy day','sunset'
  ],

  // Phrase templates for Guessing Game. Placeholders:
  // - (adj) simple adjective
  // - (noun) any lexicon entry
  // - (tag) entry with that tag (e.g., (ridable), (character), (vehicle), (food))
  // - OR use (tag1|tag2) and/or (tag1+tag2) for OR/AND tag filters
  phraseTemplates: [
    '(character) riding a (ridable)',
    '(adj) (creature) fighting a (monster)',
    '(animal) driving a (vehicle)',
    '(person) wearing a (wearable)',
    '(person) juggling (object)s',
    '(person) balancing on a (ridable)',
    '(person) hiding in a (place)',
    '(person) using a (tool) to fix a (object)',
    '(person) building a (structure) with a (tool)',
    '(person) cooking (food) in a (cookware)',
    '(person) painting a (object)',
    '(person) carrying (food) on a (ridable)',
    '(person) eating (food) with a (utensil)',
    '(animal) playing a (instrument)',
    '(person) saving a (person)',
    '(person) stuck in a (container)',
    'stack of (object)s on a (object)',
    '(adj) (object) bouncing on a (object)',
    '(vehicle) parked next to a (structure)',
    '(adj) (vehicle) flying over a (place)',
    '(person) repairing a (vehicle) with a (tool)',
    '(person) climbing a (structure)',
    '(animal) wearing a (wearable)',
    '(character) casting a spell on a (object)',
    '(person) dancing with a (character)',
    '(vehicle) made of (material)',
    '(animal) on a (ridable) in a (place)',
    '(character) trapped inside a (container)',
    '(adj) tower of (food)s',
    '(adj) (person) playing (sport)',
    '(person) surfing on a (object)',
    '(animal|creature) running from a (monster)',
    '(vehicle+space) landing on a (place)',
    '(person) flying with a (wearable)',
    '(animal) stuck in a (container) with (food)',
    'bridge of (object)s over (place)',
    '(person) cooking (food) over a (fire)',
    '(character) guarding a (object)',
    '(person) riding a (ridable) through a (weather)'
  ],

  adjectives: [
    'ancient','tiny','huge','gigantic','fluffy','spiky','slimy','shiny','rusty','colorful',
    'striped','spotted','sneaky','sleepy','grumpy','hungry','broken','glowing','golden','wooden',
    'metal','plastic','fuzzy','happy','sad','angry','sparkly','muddy','frozen','melting','glitchy','heroic',
    'clumsy','mysterious'
  ],

  // Rich word bank with tags for contextual selection
  // Add lots of specific and inanimate objects as requested
  lexicon: [
    // People and roles
    { word: 'Einstein', tags: ['person','famous'] },
    { word: 'Cleopatra', tags: ['person','famous'] },
    { word: 'Shakespeare', tags: ['person','famous','writer'] },
    { word: 'astronaut', tags: ['person','profession','character'] },
    { word: 'pirate', tags: ['person','character'] },
    { word: 'ninja', tags: ['person','character'] },
    { word: 'superhero', tags: ['person','character'] },
    { word: 'villain', tags: ['person','character'] },
    { word: 'chef', tags: ['person','profession','chef'] },
    { word: 'doctor', tags: ['person','profession'] },
    { word: 'teacher', tags: ['person','profession'] },
    { word: 'artist', tags: ['person','profession'] },
    { word: 'musician', tags: ['person','profession','musician'] },
    { word: 'farmer', tags: ['person','profession','farmer'] },
    { word: 'dancer', tags: ['person','profession'] },
    { word: 'athlete', tags: ['person','profession'] },
    { word: 'cowboy', tags: ['person','character'] },
    { word: 'detective', tags: ['person','profession','detective'] },
    { word: 'baby', tags: ['person'] },
    { word: 'knight', tags: ['person','character','armor'] },
    { word: 'princess', tags: ['person','character'] },
    { word: 'robot', tags: ['character','technology'] },
    { word: 'alien', tags: ['creature','character'] },

    // Creatures and fantasy
    { word: 'wizard', tags: ['character','creature','mythical'] },
    { word: 'witch', tags: ['character','creature','mythical'] },
    { word: 'dragon', tags: ['creature','monster','mythical','ridable'] },
    { word: 'unicorn', tags: ['creature','mythical','ridable'] },
    { word: 'mermaid', tags: ['creature','mythical'] },
    { word: 'ghost', tags: ['creature','monster'] },
    { word: 'zombie', tags: ['creature','monster'] },
    { word: 'vampire', tags: ['creature','monster'] },
    { word: 'goblin', tags: ['creature','monster'] },
    { word: 'troll', tags: ['creature','monster'] },
    { word: 'ogre', tags: ['creature','monster'] },
    { word: 'giant', tags: ['creature','mythical'] },
    { word: 'phoenix', tags: ['creature','mythical','bird'] },
    { word: 'yeti', tags: ['creature','cryptid'] },
    { word: 'bigfoot', tags: ['creature','cryptid'] },
    { word: 'fairy', tags: ['creature','mythical'] },

    // Animals
    { word: 'cat', tags: ['animal','pet'] },
    { word: 'dog', tags: ['animal','pet'] },
    { word: 'horse', tags: ['animal','ridable'] },
    { word: 'camel', tags: ['animal','ridable'] },
    { word: 'elephant', tags: ['animal','ridable'] },
    { word: 'lion', tags: ['animal'] },
    { word: 'tiger', tags: ['animal'] },
    { word: 'bear', tags: ['animal'] },
    { word: 'eagle', tags: ['animal','bird'] },
    { word: 'penguin', tags: ['animal','bird'] },
    { word: 'octopus', tags: ['animal'] },
    { word: 'whale', tags: ['animal','ridable'] },
    { word: 'shark', tags: ['animal'] },
    { word: 'dolphin', tags: ['animal','ridable'] },
    { word: 'koala', tags: ['animal'] },
    { word: 'panda', tags: ['animal'] },
    { word: 'owl', tags: ['animal','bird'] },

    // Vehicles / ridables
    { word: 'bicycle', tags: ['vehicle','ridable'] },
    { word: 'motorcycle', tags: ['vehicle','ridable'] },
    { word: 'scooter', tags: ['vehicle','ridable'] },
    { word: 'skateboard', tags: ['vehicle','ridable'] },
    { word: 'car', tags: ['vehicle','ridable'] },
    { word: 'bus', tags: ['vehicle','ridable'] },
    { word: 'train', tags: ['vehicle','ridable'] },
    { word: 'boat', tags: ['vehicle','ridable'] },
    { word: 'airplane', tags: ['vehicle','ridable'] },
    { word: 'rocket', tags: ['vehicle','ridable','space'] },
    { word: 'hoverboard', tags: ['vehicle','ridable'] },
    { word: 'submarine', tags: ['vehicle','ridable'] },
    { word: 'helicopter', tags: ['vehicle','ridable'] },
    { word: 'hot air balloon', tags: ['vehicle','ridable'] },
    { word: 'blimp', tags: ['vehicle','ridable'] },
    { word: 'spaceship', tags: ['vehicle','ridable','space'] },

    // Food and kitchen
    { word: 'pizza', tags: ['food','edible'] },
    { word: 'cake', tags: ['food','edible','dessert'] },
    { word: 'apple', tags: ['food','edible','fruit'] },
    { word: 'banana', tags: ['food','edible','fruit'] },
    { word: 'corn', tags: ['food','edible','plant'] },
    { word: 'ice cream', tags: ['food','edible','dessert'] },
    { word: 'donut', tags: ['food','edible','dessert'] },
    { word: 'cookie', tags: ['food','edible','dessert'] },
    { word: 'pie', tags: ['food','edible','dessert'] },
    { word: 'sandwich', tags: ['food','edible'] },
    { word: 'burger', tags: ['food','edible'] },
    { word: 'sushi', tags: ['food','edible'] },
    { word: 'tea', tags: ['drink'] },
    { word: 'coffee', tags: ['drink'] },
    { word: 'soda', tags: ['drink'] },
    { word: 'juice', tags: ['drink'] },
    { word: 'pan', tags: ['cookware'] },
    { word: 'pot', tags: ['cookware'] },
    { word: 'kettle', tags: ['cookware'] },
    { word: 'oven', tags: ['appliance'] },
    { word: 'spoon', tags: ['tool','utensil'] },
    { word: 'fork', tags: ['tool','utensil'] },
    { word: 'knife', tags: ['tool','utensil'] },
    { word: 'chopsticks', tags: ['utensil'] },
    { word: 'spatula', tags: ['tool','utensil'] },

    // Objects / tools / instruments
    { word: 'musket', tags: ['weapon','object'] },
    { word: 'orchestra', tags: ['group','music'] },
    { word: 'guitar', tags: ['instrument','music','object'] },
    { word: 'piano', tags: ['instrument','music','object'] },
    { word: 'violin', tags: ['instrument','music','object'] },
    { word: 'drum', tags: ['instrument','music','object'] },
    { word: 'microphone', tags: ['object','music','tool'] },
    { word: 'camera', tags: ['object','technology'] },
    { word: 'computer', tags: ['object','technology'] },
    { word: 'phone', tags: ['object','technology'] },
    { word: 'pencil', tags: ['object','tool'] },
    { word: 'paintbrush', tags: ['object','tool'] },
    { word: 'magnifying glass', tags: ['object','tool','clue'] },
    { word: 'map', tags: ['object','clue'] },
    { word: 'key', tags: ['object','tool'] },
    { word: 'lock', tags: ['object'] },
    { word: 'book', tags: ['object','book'] },
    { word: 'lantern', tags: ['object','tool','light'] },
    { word: 'flashlight', tags: ['object','tool','light'] },
    { word: 'sword', tags: ['weapon','object'] },
    { word: 'shield', tags: ['object','armor'] },
    { word: 'bow', tags: ['weapon','object'] },
    { word: 'hammer', tags: ['object','tool'] },
    { word: 'anvil', tags: ['object'] },
    { word: 'stapler', tags: ['object','tool'] },
    { word: 'microwave', tags: ['object','appliance'] },
    { word: 'bookshelf', tags: ['object','furniture'] },
    { word: 'vacuum', tags: ['object','appliance','tool'] },
    { word: 'wrench', tags: ['object','tool'] },
    { word: 'screwdriver', tags: ['object','tool'] },
    { word: 'saw', tags: ['object','tool'] },
    { word: 'ladder', tags: ['object','tool'] },
    { word: 'tennis racket', tags: ['object','sport'] },
    { word: 'soccer ball', tags: ['object','sport'] },
    { word: 'basketball', tags: ['object','sport'] },
    { word: 'baseball bat', tags: ['object','sport','tool'] },
    { word: 'trumpet', tags: ['instrument','music','object'] },
    { word: 'flute', tags: ['instrument','music','object'] },
    { word: 'saxophone', tags: ['instrument','music','object'] },
    { word: 'helmet', tags: ['wearable','object'] },
    { word: 'crown', tags: ['wearable','object'] },
    { word: 'hat', tags: ['wearable','object'] },
    { word: 'shoes', tags: ['wearable','object'] },
    { word: 'backpack', tags: ['wearable','container'] },
    { word: 'jetpack', tags: ['wearable','technology'] },
    { word: 'gloves', tags: ['wearable','object'] },
    { word: 'scarf', tags: ['wearable','object'] },
    { word: 'coat', tags: ['wearable','object'] },
    { word: 'box', tags: ['container','object'] },
    { word: 'jar', tags: ['container','object'] },
    { word: 'bucket', tags: ['container','object'] },
    { word: 'treasure chest', tags: ['container','object'] },
    { word: 'safe', tags: ['container','object'] },
    { word: 'envelope', tags: ['container','object','mail'] },
    { word: 'mailbox', tags: ['container','object','mail'] },
    { word: 'basket', tags: ['container','object'] },
    { word: 'cup', tags: ['container','object'] },
    { word: 'mug', tags: ['container','object'] },
    { word: 'bottle', tags: ['container','object'] },

    // Places / structures / materials / elements
    { word: 'castle', tags: ['structure','place'] },
    { word: 'bridge', tags: ['structure','place'] },
    { word: 'lighthouse', tags: ['structure','place'] },
    { word: 'house', tags: ['structure','place'] },
    { word: 'skyscraper', tags: ['structure','place'] },
    { word: 'tower', tags: ['structure','place'] },
    { word: 'tent', tags: ['structure'] },
    { word: 'museum', tags: ['place'] },
    { word: 'school', tags: ['place'] },
    { word: 'hospital', tags: ['place'] },
    { word: 'stadium', tags: ['place'] },
    { word: 'park', tags: ['place'] },
    { word: 'forest', tags: ['place','nature'] },
    { word: 'ocean', tags: ['place','nature'] },
    { word: 'desert', tags: ['place','nature'] },
    { word: 'volcano', tags: ['place','nature'] },
    { word: 'cloud', tags: ['place','nature','ridable'] },
    { word: 'comet', tags: ['space','object','ridable'] },
    { word: 'fire', tags: ['element','fire'] },
    { word: 'campfire', tags: ['object','fire','light'] },
    { word: 'ice', tags: ['element','material'] },
    { word: 'wind', tags: ['element','weather'] },
    { word: 'lightning', tags: ['element','weather'] },
    { word: 'rain', tags: ['weather'] },
    { word: 'snow', tags: ['weather'] },
    { word: 'storm', tags: ['weather'] },
    { word: 'rainbow', tags: ['weather','light'] },
    { word: 'stone', tags: ['material'] },
    { word: 'wood', tags: ['material'] },
    { word: 'metal', tags: ['material'] },
    { word: 'glass', tags: ['material'] },
    { word: 'paper', tags: ['material'] },
    { word: 'fabric', tags: ['material'] },
    { word: 'clay', tags: ['material'] },

    // Body parts and misc
    { word: 'hair', tags: ['body_part'] },
    { word: 'footprint', tags: ['clue'] },
    { word: 'fingerprint', tags: ['clue'] },
    { word: 'treasure', tags: ['object','treasure'] },
    { word: 'letter', tags: ['mail','object'] },
    { word: 'package', tags: ['mail','object'] },
    { word: 'plant', tags: ['plant'] },
    { word: 'flower', tags: ['plant'] },
    { word: 'tree', tags: ['plant'] },
    { word: 'cactus', tags: ['plant'] },
    { word: 'bamboo', tags: ['plant'] },
    { word: 'vine', tags: ['plant'] },
    { word: 'soccer', tags: ['sport'] },
    { word: 'tennis', tags: ['sport'] },
    { word: 'basketball', tags: ['sport'] },
    { word: 'baseball', tags: ['sport'] },
    { word: 'golf', tags: ['sport'] },
    { word: 'hockey', tags: ['sport'] },
    { word: 'volleyball', tags: ['sport'] },
    { word: 'football', tags: ['sport'] },
    { word: 'rugby', tags: ['sport'] },
    { word: 'cricket', tags: ['sport'] }
  ]
};

export default prompts;